name: ci

on:
  push:
    branches-ignore: [release]
    tags: ['*']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            README.md
            README.userscript.md
            LICENSE
      - name: Install
        uses: wyvox/action-setup-pnpm@v3
      - name: Build
        run: |
          pnpm run build:firefox
          pnpm run build:chrome
          pnpm run build:monkey
      - uses: actions/upload-artifact@v4
        with:
          name: releases
          path: releases/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: releases
      - name: Generate checksum
        run: |
          sha256sum * > sha256sum.txt
          cat sha256sum.txt
      - name: Publish github release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: '*'
          replacesArtifacts: true
          generateReleaseNotes: true
          body: |
            [更新日志](https://github.com/EhTagTranslation/EhSyringe/blob/master/CHANGELOG.md)
          prerelease: ${{ contains(github.event.ref, '-') }}
      - name: Commit release mirror
        run: |
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.name 'github-actions[bot]'
          git add .
          git commit -am 'Release for [${{ github.event.ref }}](https://github.com/EhTagTranslation/EhSyringe/tree/${{ github.event.ref }})'
          git push
