name: ci

on:
  push:
    branches-ignore: [release]
    tags: ['*']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - uses: actions/checkout@v5
      - uses: actions/upload-artifact@v5
        with:
          name: docs
          path: |
            README.md
            README.userscript.md
            LICENSE
      - name: Install
        uses: wyvox/action-setup-pnpm@v3
      - name: Download crx key
        if: github.event_name == 'push'
        run: echo "${{ secrets.CRX_KEY }}" > key.pem
      - name: Build monkey
        run: pnpm run build:monkey
      - name: Build chrome
        run: pnpm run build:chrome
      - name: Pack chrome
        if: github.event_name == 'push'
        run: pnpm run pack:chrome
      - name: Build firefox
        run: pnpm run build:firefox
      - name: Pack firefox
        run: pnpm run pack:firefox
      - name: List releases
        run: ls -lh releases/
      - uses: actions/attest-build-provenance@v3
        if: startsWith(github.event.ref, 'refs/tags/')
        with:
          subject-path: releases/
      - uses: actions/upload-artifact@v5
        with:
          name: releases
          path: releases/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.event.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v5
        with:
          ref: release
      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: docs
      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: releases
      - name: Generate checksum
        run: |
          sha256sum * > sha256sum.txt
          cat sha256sum.txt
      - name: Publish github release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: '*'
          replacesArtifacts: true
          generateReleaseNotes: true
          body: |
            [更新日志](https://github.com/EhTagTranslation/EhSyringe/blob/master/CHANGELOG.md)
          prerelease: ${{ contains(github.event.ref, '-') }}
      - name: Commit release mirror
        run: |
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.name 'github-actions[bot]'
          git add .
          git commit -am 'Release for [${{ github.event.ref }}](https://github.com/EhTagTranslation/EhSyringe/tree/${{ github.event.ref }})'
          git push
